My Project: dbbase.cpp File Reference
dbbase.cpp File Reference
数据库接口实现
#include "dbbase.h"
Functions
bool IsNativeRtu (Uint8 type)
IsNativeRtu 查看某设备是否是常规设备
bool IsSafetyRtu (Uint8 type)
IsSafetyRtu 查看某设备是否是安防设备
int init_mysql (MysqlConInfo *info)
init_mysql 初始化mysql , 连接，指定数据库
std::string get_table_name (Uint8 type)
get_table_name 根据设备类型 拿到对应的表名
static int check_connect ()
check_connect 检查连接
static int insert_mysql (string sql_cmd)
insert_mysql 数据库基本插入操作
static int db_insert_query (const string &colstr, const string &valstr, const string &tablename)
db_insert_query 数据库插入
static int DupicateKeyUpdateQuery (const string &colstr, const string &valstr, const string &updatestr, const string &tablename)
DupicateKeyUpdateQuery 更新、插入查询：存在则更新不存在则插入
static int select_query (const string &sql, string &retstr)
select_query 查找操作
static Uint32 db_select_query (const string &colstr, const string &wheresrt, const string &tablename, string &retstr)
db_select_query 查找操作
static int db_update_query (const string &setstr, const string &wherestr, const string &tablename)
db_update_query 更新查询
static int findRtuadd (Uint32 rtuadd, const string &tablename)
int findHostname (char *hostname)
findHostname 查找对应的主机名
Uint32 GetHostIdByName (char *hostname, Uint32 &hostid)
GetHostIdByName 根据主机名查找对应的ID.
int GetHostCount ()
GetHostCount 拿到 连接上来的主机个数
int insert_db_rtu (RtuRegInfo &rtuinfo)
insert_db_rtu 注册设备接口 ，将设备写入数据库
int insert_db_host (HostRegInfo &hostinfo)
insert_db_host 主机注册接口
int insert_db_sceneinfo (SceneInfo &sceneinfo)
insert_db_sceneinfo 创建、修改情景
int insert_db_apprtu (AppRtuInfo &rtuinfo)
insert_db_apprtu 添加，编辑 应用设备
int insert_db_taskinfo (TaskInfo &taskinfo)
insert_db_taskinfo 设置 编辑定时任务
int update_db_nativertu (NativeRtuInfo &rtuinfo, Uint8 mode)
update_db_nativertu 常规设备更新
int update_db_safetyrtu (SafetyRtu &rtuinfo)
update_db_safetyrtu 更新安防设备
int update_db_sceneinfo (SceneInfo &rtuinfo)
update_db_sceneinfo 修改 情景
int update_db_apprtu (AppRtuInfo &rtuinfo)
update_db_apprtu 修改应用设备
int update_db_host (HostRegInfo &hostinfo)
update_db_host 更新主机信息表
int update_db_hostname (HostMan &hostinfo)
update_db_hostname 用户管理
int update_db_rtuinfo (RtuUpdate &hostinfo)
update_db_rtuinfo 用户设备信息编辑
int update_db_scenertu (SceneRtu &rtuinfo)
update_db_scenertu 更新情景面板
int update_db_exnativertu (ExNativeRtu &rtuinfo)
update_db_exnativertu 更新智能床
int update_db_taskinfo (TaskInfo &taskinfo)
update_db_taskinfo 编辑定时任务
int update_db_detectorrtu (DetectorRtu &rtuinfo, Uint8 mode)
update_db_detectorrtu 更新传感器设备
int update_db_detectorbind (DetectorBind &rtuinfo)
update_db_detectorbind 绑定联动接口
int update_db_safetypwd (SafetyPwdInfo &rtuinfo)
update_db_safetypwd 门锁密码更新接口 包括新开锁密码添加，修改 管理员密码修改
int select_db_hostinfo (HostRegInfo *pHostinfo, char *hostname)
select_db_hostinfo 根据主机名 查询主机信息 ，用于 APP远程登陆
int delete_db_host (char *hostname)
delete_db_host 删除主机设备
int delete_db_rtu (RtuRemoveInfo &rtuinfo)
delete_db_rtu 删除设备 接口 不包括删除主机
Uint32 GetIpByHostAdd (Uint32 hostadd, Uint32 &hostip)
Variables
MYSQL m_mysqlfd
Detailed Description
数据库接口实现
增删查改
Author
menqi - 10837.nosp@m.3487.nosp@m.6@qq..nosp@m.com
Date
2016-05-06 16:45
Version
1.0
Copyright (c): menqi
Function Documentation
static int check_connect () static
check_connect 检查连接
Returns
References m_mysqlfd.
Referenced by db_insert_query(), db_update_query(), delete_db_host(), delete_db_rtu(), DupicateKeyUpdateQuery(), findHostname(), findRtuadd(), GetHostCount(), GetHostIdByName(), GetIpByHostAdd(), and select_query().
static int db_insert_query (const string & colstr, const string & valstr, const string & tablename) static
db_insert_query 数据库插入
Parameters
colstr 列字段
valstr 值字段
tablename 数据表名
Returns
References check_connect(), insert_mysql(), LOG_DEBUG, and LOG_ERROR.
Referenced by insert_db_host(), and insert_db_rtu().
static Uint32 db_select_query (const string & colstr, const string & wheresrt, const string & tablename, string & retstr) static
db_select_query 查找操作
Parameters
colstr 列字段
wheresrt 过滤字段
tablename 表名
retstr 查找结果
Returns
References LOG_DEBUG, LOG_ERROR, and select_query().
Referenced by select_db_hostinfo(), update_db_hostname(), and update_db_safetypwd().
static int db_update_query (const string & setstr, const string & wherestr, const string & tablename) static
db_update_query 更新查询
Parameters
setstr 设置字符串
wherestr 条件字符串
tablename 表名
Returns
References check_connect(), LOG_DEBUG, and m_mysqlfd.
Referenced by update_db_detectorbind(), update_db_detectorrtu(), update_db_exnativertu(), update_db_host(), update_db_hostname(), update_db_nativertu(), update_db_rtuinfo(), update_db_safetypwd(), update_db_safetyrtu(), and update_db_scenertu().
int delete_db_host (char * hostname)
delete_db_host 删除主机设备
Parameters
hostname 主机名
Returns
References check_connect(), DB_TABLE_NAMELIST, LOG_DEBUG, LOG_ERROR, m_mysqlfd, and MAX_DB_TYPE.
int delete_db_rtu (RtuRemoveInfo & rtuinfo)
delete_db_rtu 删除设备 接口 不包括删除主机
Parameters
rtuinfo
Returns
-1 删除出错 0 删除成功 或者 没有删除项
References check_connect(), get_table_name(), RtuRemoveInfo::hostadd, LOG_DEBUG, LOG_ERROR, m_mysqlfd, RtuRemoveInfo::rtuadd, and RtuRemoveInfo::rtutype.
Referenced by main().
static int DupicateKeyUpdateQuery (const string & colstr, const string & valstr, const string & updatestr, const string & tablename) static
DupicateKeyUpdateQuery 更新、插入查询：存在则更新不存在则插入
Parameters
colstr 列
valstr 值
updatestr 要更新的列
tablename 表名
Returns
References check_connect(), LOG_DEBUG, and m_mysqlfd.
Referenced by insert_db_apprtu(), insert_db_sceneinfo(), and insert_db_taskinfo().
int findHostname (char * hostname)
findHostname 查找对应的主机名
Parameters
hostname 主机名
Returns
返回值 -1 错误 0 没有找到对应的 >0 找到的主机个数
References check_connect(), LOG_ERROR, and m_mysqlfd.
Referenced by insert_db_host(), and update_db_host().
static int findRtuadd (Uint32 rtuadd, const string & tablename) static
查看对应的设备是否已经存在
References check_connect(), LOG_ERROR, and m_mysqlfd.
Referenced by insert_db_rtu().
std::string get_table_name (Uint8 type)
get_table_name 根据设备类型 拿到对应的表名
Parameters
type 设备类型
Returns
表名 为 string 类型
References gTypeInfoList, and DBTypeInfo::tablename.
Referenced by delete_db_rtu(), insert_db_rtu(), update_db_exnativertu(), update_db_host(), update_db_rtuinfo(), and update_db_safetyrtu().
int GetHostCount ()
GetHostCount 拿到 连接上来的主机个数
Returns
主机个数
References check_connect(), LOG_DEBUG, LOG_ERROR, and m_mysqlfd.
Uint32 GetHostIdByName (char * hostname, Uint32 & hostid)
GetHostIdByName 根据主机名查找对应的ID.
Parameters
hostname 主机名
hostid 找到的hostadd放入该参数
Returns
-1 查找错误 0 查找正确
References check_connect(), LOG_DEBUG, LOG_ERROR, and m_mysqlfd.
Uint32 GetIpByHostAdd (Uint32 hostadd, Uint32 & hostip)
根据 hostadd 拿到 ip
References check_connect(), LOG_DEBUG, LOG_ERROR, and m_mysqlfd.
int init_mysql (MysqlConInfo * info)
init_mysql 初始化mysql , 连接，指定数据库
Parameters
info 连接mysql时，mysql相关信息结构体
Returns
0 成功 -1 失败
References MysqlConInfo::dbname, MysqlConInfo::hostname, m_mysqlfd, MysqlConInfo::password, and MysqlConInfo::username.
Referenced by main().
int insert_db_apprtu (AppRtuInfo & rtuinfo)
insert_db_apprtu 添加，编辑 应用设备
Parameters
rtuinfo 应用设备结构体
Returns
References DB_TABLE_NAMELIST, DupicateKeyUpdateQuery(), AppRtuInfo::hostadd, AppRtuInfo::irrtuadd, LOG_ERROR, RTU_STATE_VALID, AppRtuInfo::rtuadd, AppRtuInfo::rtuname, AppRtuInfo::rturegtime, and AppRtuInfo::rtutype.
Referenced by update_db_apprtu().
int insert_db_host (HostRegInfo & hostinfo)
insert_db_host 主机注册接口
Parameters
hostinfo 主机信息结构体
Returns
-1 插入失败 0 插入成功 >0 主机名字已经存在
References db_insert_query(), DB_TABLE_NAMELIST, findHostname(), HostRegInfo::hostadd, HostRegInfo::hostip, HostRegInfo::hostname, HostRegInfo::hostpwd, HostRegInfo::hostregtime, HostRegInfo::lastcomtime, LOG_ERROR, LOG_PRINT, and RTU_STATE_VALID.
int insert_db_rtu (RtuRegInfo & rtuinfo)
insert_db_rtu 注册设备接口 ，将设备写入数据库
Parameters
rtuinfo 插入设备结构体
Returns
-1 插入失败 0 插入成功
References db_insert_query(), DB_TABLE_NAMELIST, findRtuadd(), get_table_name(), RtuRegInfo::hostadd, LOG_ERROR, m_mysqlfd, RtuRegInfo::rtuadd, RtuRegInfo::rturegtime, RtuRegInfo::rtustate, and RtuRegInfo::rtutype.
int insert_db_sceneinfo (SceneInfo & sceneinfo)
insert_db_sceneinfo 创建、修改情景
Parameters
sceneinfo 情景信息结构体 绑定的设备信息需要malloc后传入
Returns
References RtuBind::add, DB_TABLE_NAMELIST, RtuBind::delay, DupicateKeyUpdateQuery(), SceneInfo::hostadd, LOG_ERROR, RtuBind::oper, SceneInfo::rtubind, SceneInfo::rturegtime, SceneInfo::sceneid, SceneInfo::scenename, SceneInfo::scenepicid, SceneInfo::scenertunum, and RtuBind::type.
Referenced by update_db_sceneinfo().
int insert_db_taskinfo (TaskInfo & taskinfo)
insert_db_taskinfo 设置 编辑定时任务
Parameters
taskinfo 任务信息 绑定的设备信息需要malloc后传入
References RtuBind::add, DB_TABLE_NAMELIST, RtuBind::delay, DupicateKeyUpdateQuery(), TaskInfo::hostadd, LOG_ERROR, RtuBind::oper, TaskInfo::rtubind, TaskInfo::taskcycle, TaskInfo::taskid, TaskInfo::taskname, TaskInfo::taskpicid, TaskInfo::taskregtime, TaskInfo::taskrtunum, TaskInfo::taskstdtime, and RtuBind::type.
Referenced by update_db_taskinfo().
static int insert_mysql (string sql_cmd) static
insert_mysql 数据库基本插入操作
Parameters
sql_cmd 插入命令 为string 类型
Returns
References LOG_ERROR, and m_mysqlfd.
Referenced by db_insert_query().
bool IsNativeRtu (Uint8 type)
IsNativeRtu 查看某设备是否是常规设备
Parameters
type 设备类型
Returns
true or false
References RTU_TYPE_CTRLBOX, RTU_TYPE_CURTAIN, RTU_TYPE_PLUG, RTU_TYPE_RGB, RTU_TYPE_ROBTIC, and RTU_TYPE_SWITCH.
Referenced by update_db_rtuinfo().
bool IsSafetyRtu (Uint8 type)
IsSafetyRtu 查看某设备是否是安防设备
Parameters
type 设备类型
Returns
true or false
References RTU_TYPE_DOORBELL, RTU_TYPE_DOORCONTACT, RTU_TYPE_DOORLOCK, and RTU_TYPE_IRPROBE.
int select_db_hostinfo (HostRegInfo * pHostinfo, char * hostname)
select_db_hostinfo 根据主机名 查询主机信息 ，用于 APP远程登陆
Parameters
pHostinfo
hostname HostAdd,HostPwd,HostIp,HostState,LastComTime
Returns
返回值 -1 错误 0 正确 1 没有数据
References db_select_query(), DB_TABLE_NAMELIST, HostRegInfo::hostadd, HostRegInfo::hostip, HostRegInfo::hostpwd, HostRegInfo::hoststate, HostRegInfo::lastcomtime, LOG_DEBUG, and LOG_ERROR.
static int select_query (const string & sql, string & retstr) static
select_query 查找操作
Parameters
sql 查找sql 命令
retstr 返回列字段，以逗号隔开
Returns
References check_connect(), LOG_DEBUG, LOG_ERROR, and m_mysqlfd.
Referenced by db_select_query().
int update_db_apprtu (AppRtuInfo & rtuinfo)
update_db_apprtu 修改应用设备
References insert_db_apprtu().
int update_db_detectorbind (DetectorBind & rtuinfo)
update_db_detectorbind 绑定联动接口
Parameters
rtuinfo 绑定的设备信息需要malloc后传入
References RtuBind::add, DetectorBind::bind_num, db_update_query(), RtuBind::delay, DetectorBind::hostadd, DetectorBind::level, RtuBind::oper, DetectorBind::rtuadd, DetectorBind::rtubind, and RtuBind::type.
int update_db_detectorrtu (DetectorRtu & rtuinfo, Uint8 mode)
update_db_detectorrtu 更新传感器设备
Parameters
rtuinfo
mode 模式 0 更新 val 值 1 更新联动标志，阈值 更新val : 传入 val数组值 ,默认为0 更新联动标志： 传入 flag ,downval ,upval
Returns
References db_update_query(), DetectorRtu::detectorinfo, DetectorInfo::downval, DetectorInfo::flag, RtuRegInfo::hostadd, LOG_ERROR, RtuRegInfo::rtuadd, DetectorRtu::rtuinfo, DetectorInfo::upval, DetectorInfo::val, and DetectorRtu::valtype.
int update_db_exnativertu (ExNativeRtu & rtuinfo)
update_db_exnativertu 更新智能床
Parameters
rtuinfo 控制 ： relayinfo 数组 中val值传入 床头位置（1） 床尾位置（1） 床头振动（1） 床尾振动（1） 灯状态（1）：0x00表示关灯，0x01表示开灯
Returns
References db_update_query(), get_table_name(), RtuRegInfo::hostadd, ExNativeRtu::relayinfo, RTU_TYPE_BED, RtuRegInfo::rtuadd, ExNativeRtu::rtuinfo, and RelayInfo::val.
int update_db_host (HostRegInfo & hostinfo)
update_db_host 更新主机信息表
Parameters
hostinfo 更新信息： 传入 hostname ,hostip
Returns
References db_update_query(), findHostname(), get_sys_time(), get_table_name(), HostRegInfo::hostip, HostRegInfo::hostname, LOG_ERROR, and RTU_TYPE_HOST.
int update_db_hostname (HostMan & hostinfo)
update_db_hostname 用户管理
Parameters
hostinfo 更新信息： 传入 原 新 主机名 密码
Returns
References db_select_query(), db_update_query(), MAX_PASSWORD_LEN, HostMan::newname, HostMan::newpwd, HostMan::oldname, and HostMan::oldpwd.
int update_db_nativertu (NativeRtuInfo & rtuinfo, Uint8 mode)
update_db_nativertu 常规设备更新
Parameters
rtuinfo
mode 模式 0 控制 1 绑定负载 控制 ： 传入 RelayInfo 数组中 val 绑定负载： 传入 bind_num , RelayInfo 数组中 id,type,name[] ,path[] 设备头信息 RtuRegInfo 中的hostadd,rtuadd 必须传入
Returns
0 更新成功 -1 更新失败
References NativeRtuInfo::bind_num, db_update_query(), RtuRegInfo::hostadd, RelayInfo::id, LOG_DEBUG, LOG_ERROR, RelayInfo::name, RelayInfo::path, NativeRtuInfo::relayinfo, RtuRegInfo::rtuadd, NativeRtuInfo::rtuinfo, RelayInfo::type, and RelayInfo::val.
int update_db_rtuinfo (RtuUpdate & hostinfo)
update_db_rtuinfo 用户设备信息编辑
Parameters
hostinfo 该结构体所有字段必须传入 更新 设备名称和路径
Returns
References db_update_query(), get_table_name(), RtuUpdate::hostadd, IsNativeRtu(), RtuUpdate::opertype, RTU_TYPE_BED, RTU_TYPE_SCENEINFO, RTU_TYPE_TASKINFO, RtuUpdate::rtuadd, RtuUpdate::rtuname, RtuUpdate::rtupath, and RtuUpdate::rtutype.
int update_db_safetypwd (SafetyPwdInfo & rtuinfo)
update_db_safetypwd 门锁密码更新接口 包括新开锁密码添加，修改 管理员密码修改
References db_select_query(), db_update_query(), SafetyPwdInfo::hostadd, SafetyPwdInfo::id, LOG_ERROR, MAX_PASSWORD_LEN, SafetyPwdInfo::newpwd, SafetyPwdInfo::oldpwd, and SafetyPwdInfo::rtuadd.
int update_db_safetyrtu (SafetyRtu & rtuinfo)
update_db_safetyrtu 更新安防设备
Parameters
rtuinfo 控制： 传入 布防状态 ， 动作状态 hostadd ,rtuadd 必须 传入
Returns
References db_update_query(), get_table_name(), RtuRegInfo::hostadd, SafetyRtu::rtuactstate, RtuRegInfo::rtuadd, SafetyRtu::rtuinfo, SafetyRtu::rtuplace, and RtuRegInfo::rtutype.
int update_db_sceneinfo (SceneInfo & rtuinfo)
update_db_sceneinfo 修改 情景
References insert_db_sceneinfo().
Referenced by main().
int update_db_scenertu (SceneRtu & rtuinfo)
update_db_scenertu 更新情景面板
Parameters
rtuinfo 修改绑定： bind_num , 每个button的信息 ，包括id ,type,add,oper
Returns
References SceneBind::add, SceneRtu::bind_num, db_update_query(), RtuRegInfo::hostadd, SceneBind::id, SceneBind::oper, RtuRegInfo::rtuadd, SceneRtu::rtuinfo, SceneRtu::scene_bind, and SceneBind::type.
int update_db_taskinfo (TaskInfo & taskinfo)
update_db_taskinfo 编辑定时任务
References insert_db_taskinfo().
Referenced by main().
Variable Documentation
MYSQL m_mysqlfd
数据库连接描述符
Referenced by check_connect(), db_update_query(), delete_db_host(), delete_db_rtu(), DupicateKeyUpdateQuery(), findHostname(), findRtuadd(), GetHostCount(), GetHostIdByName(), GetIpByHostAdd(), init_mysql(), insert_db_rtu(), insert_mysql(), and select_query().