My Project: dbbase.h File Reference
dbbase.h File Reference
mysql 数据库接口实现
#include <stdio.h>
#include <mysql/mysql.h>
#include <sstream>
#include <iostream>
#include <string.h>
#include "base.h"
Data Structures
struct DBTypeInfo
struct MysqlConInfo
struct RtuRegInfo
struct RtuRemoveInfo
struct HostRegInfo
struct AppRtuInfo
struct RelayInfo
struct NativeRtuInfo
struct SafetyRtu
struct SceneBind
struct SceneRtu
struct ExNativeRtu
struct DetectorInfo
struct DetectorRtu
struct RtuBind
struct DetectorBind
struct TaskInfo
struct SceneInfo
struct HostMan
struct RtuUpdate
struct SafetyPwdInfo
Macros
#define MAX_SQLNAME_LEN 256
数据库主机长度
#define MAX_USERNAME_LEN 32
用户名长度
#define MAX_PASSWORD_LEN 16
用户密码长度
#define MAX_SQLUSERNAME_LEN 16
数据库用户名长度
#define MAX_SQLPASSWD_LEN 32
数据库密码
#define MIN_PATH_LEN 32
最小路径名长度
#define MAX_NAME_LEN 32
最大名称描述长度
#define DB_TYPE_HOSTINFO 0
主机信息
#define DB_TYPE_NATIVERTU 1
常规设备数据对象类型，即对应设备类型中的智能开关、智能插座、继电器控制盒、RGB灯、窗帘控制器
#define DB_TYPE_SCENERTU 2
情景面板数据对象类型，即对应设备类型中的情景面板
#define DB_TYPE_SCENEINFO 3
情景信息数据对象类型，与设备类型无关
#define DB_TYPE_TRANSPOND 4
转发设备数据对象类型，即对应设备类型中的蓝牙遥控器、红外转发器
#define DB_TYPE_USEDEVICE 5
应用设备对象类型，即对应设备类型中的应用设备
#define DB_TYPE_SAFETY 6
安防设备数据对象类型，即对应设备类型中的红外入侵探测器、智能门磁、智能门锁、智能门铃
#define DB_TYPE_SAFETY_PWD 7
安防设备数据的密码
#define DB_TYPE_SAFETY_SET 8
安防设备数据的设防联动
#define DB_TYPE_SAFETY_REMOVE 9
安防设备数据的撤防联动
#define DB_TYPE_SCENEINFO_CON 10
情景信息续表
#define DB_TYPE_DETECTORRTU 11
传感器设备数据对象类型
#define DB_TYPE_DETECTORBIND 12
传感器设备联动
#define DB_TYPE_TASKINFO 13
#define DB_TYPE_EXNATIVERTU 14
#define MAX_DB_TYPE 15
#define DB_TYPE_RTUTYPE (MAX_DB_TYPE)
#define DB_TYPE_USEDEVTYPE (MAX_DB_TYPE+1)
#define RTU_TYPE_HOST 0
主机类型
#define RTU_TYPE_SWITCH 1
智能开关类型
#define RTU_TYPE_SCENE 2
情景面板类型
#define RTU_TYPE_PLUG 3
智能插座类型
#define RTU_TYPE_CTRLBOX 4
继电器控制盒类型
#define RTU_TYPE_RGB 5
RGB灯
#define RTU_TYPE_BTREMOTE 6
蓝牙遥控器
#define RTU_TYPE_IRTRANS 7
红外转发器
#define RTU_TYPE_CURTAIN 8
窗帘控制器
#define RTU_TYPE_IRPROBE 9
红外入侵探测器
#define RTU_TYPE_DOORCONTACT 10
智能门磁
#define RTU_TYPE_DOORLOCK 11
智能门锁
#define RTU_TYPE_DOORBELL 12
智能门铃
#define RTU_TYPE_LIGHTDET 13
光照探测器
#define RTU_TYPE_GASDET 14
可燃气探测器
#define RTU_TYPE_TPMHUMDET 15
温湿度空气质量探测器
#define RTU_TYPE_DAMDET 16
湿敏探测器
#define RTU_TYPE_ROBTIC 17
机械手
#define RTU_TYPE_BED 18
智能床
#define RTU_TYPE_USERINFO 0xf8
用户信息
#define RTU_TYPE_FLOORINFO 0xf9
楼层信息
#define RTU_TYPE_USEDEVICE 0xfa
应用设备，如用户的电视、空调、机机盒、摄像头
#define RTU_TYPE_SERVER 0xfb
#define RTU_TYPE_TASKINFO 0xfc
任务信息，即存储的数据
#define RTU_TYPE_SCENEINFO 0xfd
情景信息，即存储的数据
#define RTU_TYPE_APP 0xfe
APP应用程序
#define RTU_TYPE_INVALID 0xff
无效
#define MIN_RTU_TYPE (RTU_TYPE_HOST)
#define MAX_RTU_TYPE ((RTU_TYPE_BED)+1)
Enumerations
enum Rtustatus { RTU_STATE_NEW = 1, RTU_STATE_REG, RTU_STATE_VALID, RTU_STATE_INVALID }
Functions
int init_mysql (MysqlConInfo *info)
init_mysql 初始化mysql , 连接，指定数据库
int findHostname (char *hostname)
findHostname 查找对应的主机名
Uint32 GetHostIdByName (char *hostname, Uint32 &hostid)
GetHostIdByName 根据主机名查找对应的ID.
int GetHostCount ()
GetHostCount 拿到 连接上来的主机个数
std::string get_table_name (Uint8 type)
get_table_name 根据设备类型 拿到对应的表名
int insert_db_rtu (RtuRegInfo &rtuinfo)
insert_db_rtu 注册设备接口 ，将设备写入数据库
int insert_db_host (HostRegInfo &hostinfo)
insert_db_host 主机注册接口
int insert_db_sceneinfo (SceneInfo &sceneinfo)
insert_db_sceneinfo 创建、修改情景
int insert_db_apprtu (AppRtuInfo &rtuinfo)
insert_db_apprtu 添加，编辑 应用设备
int insert_db_taskinfo (TaskInfo &taskinfo)
insert_db_taskinfo 设置 编辑定时任务
int update_db_nativertu (NativeRtuInfo &rtuinfo, Uint8 mode)
update_db_nativertu 常规设备更新
int update_db_safetyrtu (SafetyRtu &rtuinfo)
update_db_safetyrtu 更新安防设备
int update_db_sceneinfo (SceneInfo &rtuinfo)
update_db_sceneinfo 修改 情景
int update_db_host (HostRegInfo &hostinfo)
update_db_host 更新主机信息表
int update_db_scenertu (SceneRtu &rtuinfo)
update_db_scenertu 更新情景面板
int update_db_apprtu (AppRtuInfo &rtuinfo)
update_db_apprtu 修改应用设备
int update_db_exnativertu (ExNativeRtu &rtuinfo)
update_db_exnativertu 更新智能床
int update_db_taskinfo (TaskInfo &taskinfo)
update_db_taskinfo 编辑定时任务
int update_db_hostname (HostMan &hostinfo)
update_db_hostname 用户管理
int update_db_rtuinfo (RtuUpdate &hostinfo)
update_db_rtuinfo 用户设备信息编辑
int update_db_detectorrtu (DetectorRtu &rtuinfo, Uint8 mode)
update_db_detectorrtu 更新传感器设备
int update_db_detectorbind (DetectorBind &rtuinfo)
update_db_detectorbind 绑定联动接口
int update_db_safetypwd (SafetyPwdInfo &rtuinfo)
update_db_safetypwd 门锁密码更新接口 包括新开锁密码添加，修改 管理员密码修改
int select_db_hostinfo (HostRegInfo *pHostinfo, char *hostname)
select_db_hostinfo 根据主机名 查询主机信息 ，用于 APP远程登陆
int delete_db_rtu (RtuRemoveInfo &rtuinfo)
delete_db_rtu 删除设备 接口 不包括删除主机
int delete_db_host (char *hostname)
delete_db_host 删除主机设备
Uint32 GetIpByHostAdd (Uint32 hostadd, Uint32 &hostip)
Variables
const char DB_TABLE_NAMELIST [][32]
static DBTypeInfo gTypeInfoList []
Detailed Description
mysql 数据库接口实现
Author
menqi - 10837.nosp@m.3487.nosp@m.6@qq..nosp@m.com
Date
2016-05-06 16:43
Version
1.0
Copyright (c): menqi
Macro Definition Documentation
#define DB_TYPE_DETECTORBIND 12
传感器设备联动
#define DB_TYPE_DETECTORRTU 11
传感器设备数据对象类型
#define DB_TYPE_EXNATIVERTU 14
#define DB_TYPE_HOSTINFO 0
主机信息
#define DB_TYPE_NATIVERTU 1
常规设备数据对象类型，即对应设备类型中的智能开关、智能插座、继电器控制盒、RGB灯、窗帘控制器
#define DB_TYPE_RTUTYPE (MAX_DB_TYPE)
#define DB_TYPE_SAFETY 6
安防设备数据对象类型，即对应设备类型中的红外入侵探测器、智能门磁、智能门锁、智能门铃
#define DB_TYPE_SAFETY_PWD 7
安防设备数据的密码
#define DB_TYPE_SAFETY_REMOVE 9
安防设备数据的撤防联动
#define DB_TYPE_SAFETY_SET 8
安防设备数据的设防联动
#define DB_TYPE_SCENEINFO 3
情景信息数据对象类型，与设备类型无关
#define DB_TYPE_SCENEINFO_CON 10
情景信息续表
#define DB_TYPE_SCENERTU 2
情景面板数据对象类型，即对应设备类型中的情景面板
#define DB_TYPE_TASKINFO 13
#define DB_TYPE_TRANSPOND 4
转发设备数据对象类型，即对应设备类型中的蓝牙遥控器、红外转发器
#define DB_TYPE_USEDEVICE 5
应用设备对象类型，即对应设备类型中的应用设备
#define DB_TYPE_USEDEVTYPE (MAX_DB_TYPE+1)
#define MAX_DB_TYPE 15
Referenced by delete_db_host().
#define MAX_NAME_LEN 32
最大名称描述长度
#define MAX_PASSWORD_LEN 16
用户密码长度
Referenced by update_db_hostname(), and update_db_safetypwd().
#define MAX_RTU_TYPE ((RTU_TYPE_BED)+1)
#define MAX_SQLNAME_LEN 256
数据库主机长度
#define MAX_SQLPASSWD_LEN 32
数据库密码
#define MAX_SQLUSERNAME_LEN 16
数据库用户名长度
#define MAX_USERNAME_LEN 32
用户名长度
#define MIN_PATH_LEN 32
最小路径名长度
#define MIN_RTU_TYPE (RTU_TYPE_HOST)
#define RTU_TYPE_APP 0xfe
APP应用程序
#define RTU_TYPE_BED 18
智能床
Referenced by update_db_exnativertu(), and update_db_rtuinfo().
#define RTU_TYPE_BTREMOTE 6
蓝牙遥控器
#define RTU_TYPE_CTRLBOX 4
继电器控制盒类型
Referenced by IsNativeRtu().
#define RTU_TYPE_CURTAIN 8
窗帘控制器
Referenced by IsNativeRtu().
#define RTU_TYPE_DAMDET 16
湿敏探测器
#define RTU_TYPE_DOORBELL 12
智能门铃
Referenced by IsSafetyRtu().
#define RTU_TYPE_DOORCONTACT 10
智能门磁
Referenced by IsSafetyRtu().
#define RTU_TYPE_DOORLOCK 11
智能门锁
Referenced by IsSafetyRtu().
#define RTU_TYPE_FLOORINFO 0xf9
楼层信息
#define RTU_TYPE_GASDET 14
可燃气探测器
#define RTU_TYPE_HOST 0
主机类型
Referenced by update_db_host().
#define RTU_TYPE_INVALID 0xff
无效
#define RTU_TYPE_IRPROBE 9
红外入侵探测器
Referenced by IsSafetyRtu().
#define RTU_TYPE_IRTRANS 7
红外转发器
#define RTU_TYPE_LIGHTDET 13
光照探测器
#define RTU_TYPE_PLUG 3
智能插座类型
Referenced by IsNativeRtu().
#define RTU_TYPE_RGB 5
RGB灯
Referenced by IsNativeRtu().
#define RTU_TYPE_ROBTIC 17
机械手
Referenced by IsNativeRtu().
#define RTU_TYPE_SCENE 2
情景面板类型
#define RTU_TYPE_SCENEINFO 0xfd
情景信息，即存储的数据
Referenced by main(), and update_db_rtuinfo().
#define RTU_TYPE_SERVER 0xfb
#define RTU_TYPE_SWITCH 1
智能开关类型
Referenced by IsNativeRtu().
#define RTU_TYPE_TASKINFO 0xfc
任务信息，即存储的数据
Referenced by update_db_rtuinfo().
#define RTU_TYPE_TPMHUMDET 15
温湿度空气质量探测器
#define RTU_TYPE_USEDEVICE 0xfa
应用设备，如用户的电视、空调、机机盒、摄像头
#define RTU_TYPE_USERINFO 0xf8
用户信息
Enumeration Type Documentation
enum Rtustatus
设备注册状态
Enumerator:
RTU_STATE_NEW
新加状态，如注册过程中刚找到还没有上送到APP
RTU_STATE_REG
注册过程状态，即APP已经知道该设备存在，但还没有允许设备注册到主机中的一种状态
RTU_STATE_VALID
有效状态，即已经允许注册到主机中，
RTU_STATE_INVALID
无效状态，如删除后的状态
Function Documentation
int delete_db_host (char * hostname)
delete_db_host 删除主机设备
Parameters
hostname 主机名
Returns
References check_connect(), DB_TABLE_NAMELIST, LOG_DEBUG, LOG_ERROR, m_mysqlfd, and MAX_DB_TYPE.
int delete_db_rtu (RtuRemoveInfo & rtuinfo)
delete_db_rtu 删除设备 接口 不包括删除主机
Parameters
rtuinfo
Returns
-1 删除出错 0 删除成功 或者 没有删除项
References check_connect(), get_table_name(), RtuRemoveInfo::hostadd, LOG_DEBUG, LOG_ERROR, m_mysqlfd, RtuRemoveInfo::rtuadd, and RtuRemoveInfo::rtutype.
Referenced by main().
int findHostname (char * hostname)
findHostname 查找对应的主机名
Parameters
hostname 主机名
Returns
返回值 -1 错误 0 没有找到对应的 >0 找到的主机个数
References check_connect(), LOG_ERROR, and m_mysqlfd.
Referenced by insert_db_host(), and update_db_host().
std::string get_table_name (Uint8 type)
get_table_name 根据设备类型 拿到对应的表名
Parameters
type 设备类型
Returns
表名 为 string 类型
References gTypeInfoList, and DBTypeInfo::tablename.
Referenced by delete_db_rtu(), insert_db_rtu(), update_db_exnativertu(), update_db_host(), update_db_rtuinfo(), and update_db_safetyrtu().
int GetHostCount ()
GetHostCount 拿到 连接上来的主机个数
Returns
主机个数
References check_connect(), LOG_DEBUG, LOG_ERROR, and m_mysqlfd.
Uint32 GetHostIdByName (char * hostname, Uint32 & hostid)
GetHostIdByName 根据主机名查找对应的ID.
Parameters
hostname 主机名
hostid 找到的hostadd放入该参数
Returns
-1 查找错误 0 查找正确
References check_connect(), LOG_DEBUG, LOG_ERROR, and m_mysqlfd.
Uint32 GetIpByHostAdd (Uint32 hostadd, Uint32 & hostip)
根据主机地址获取 主机ip
根据 hostadd 拿到 ip
References check_connect(), LOG_DEBUG, LOG_ERROR, and m_mysqlfd.
int init_mysql (MysqlConInfo * info)
init_mysql 初始化mysql , 连接，指定数据库
Parameters
info 连接mysql时，mysql相关信息结构体
Returns
0 成功 -1 失败
References MysqlConInfo::dbname, MysqlConInfo::hostname, m_mysqlfd, MysqlConInfo::password, and MysqlConInfo::username.
Referenced by main().
int insert_db_apprtu (AppRtuInfo & rtuinfo)
insert_db_apprtu 添加，编辑 应用设备
Parameters
rtuinfo 应用设备结构体
Returns
References DB_TABLE_NAMELIST, DupicateKeyUpdateQuery(), AppRtuInfo::hostadd, AppRtuInfo::irrtuadd, LOG_ERROR, RTU_STATE_VALID, AppRtuInfo::rtuadd, AppRtuInfo::rtuname, AppRtuInfo::rturegtime, and AppRtuInfo::rtutype.
Referenced by update_db_apprtu().
int insert_db_host (HostRegInfo & hostinfo)
insert_db_host 主机注册接口
Parameters
hostinfo 主机信息结构体
Returns
-1 插入失败 0 插入成功 >0 主机名字已经存在
References db_insert_query(), DB_TABLE_NAMELIST, findHostname(), HostRegInfo::hostadd, HostRegInfo::hostip, HostRegInfo::hostname, HostRegInfo::hostpwd, HostRegInfo::hostregtime, HostRegInfo::lastcomtime, LOG_ERROR, LOG_PRINT, and RTU_STATE_VALID.
int insert_db_rtu (RtuRegInfo & rtuinfo)
insert_db_rtu 注册设备接口 ，将设备写入数据库
Parameters
rtuinfo 插入设备结构体
Returns
-1 插入失败 0 插入成功
References db_insert_query(), DB_TABLE_NAMELIST, findRtuadd(), get_table_name(), RtuRegInfo::hostadd, LOG_ERROR, m_mysqlfd, RtuRegInfo::rtuadd, RtuRegInfo::rturegtime, RtuRegInfo::rtustate, and RtuRegInfo::rtutype.
int insert_db_sceneinfo (SceneInfo & sceneinfo)
insert_db_sceneinfo 创建、修改情景
Parameters
sceneinfo 情景信息结构体 绑定的设备信息需要malloc后传入
Returns
References RtuBind::add, DB_TABLE_NAMELIST, RtuBind::delay, DupicateKeyUpdateQuery(), SceneInfo::hostadd, LOG_ERROR, RtuBind::oper, SceneInfo::rtubind, SceneInfo::rturegtime, SceneInfo::sceneid, SceneInfo::scenename, SceneInfo::scenepicid, SceneInfo::scenertunum, and RtuBind::type.
Referenced by update_db_sceneinfo().
int insert_db_taskinfo (TaskInfo & taskinfo)
insert_db_taskinfo 设置 编辑定时任务
Parameters
taskinfo 任务信息 绑定的设备信息需要malloc后传入
References RtuBind::add, DB_TABLE_NAMELIST, RtuBind::delay, DupicateKeyUpdateQuery(), TaskInfo::hostadd, LOG_ERROR, RtuBind::oper, TaskInfo::rtubind, TaskInfo::taskcycle, TaskInfo::taskid, TaskInfo::taskname, TaskInfo::taskpicid, TaskInfo::taskregtime, TaskInfo::taskrtunum, TaskInfo::taskstdtime, and RtuBind::type.
Referenced by update_db_taskinfo().
int select_db_hostinfo (HostRegInfo * pHostinfo, char * hostname)
select_db_hostinfo 根据主机名 查询主机信息 ，用于 APP远程登陆
Parameters
pHostinfo
hostname HostAdd,HostPwd,HostIp,HostState,LastComTime
Returns
返回值 -1 错误 0 正确 1 没有数据
References db_select_query(), DB_TABLE_NAMELIST, HostRegInfo::hostadd, HostRegInfo::hostip, HostRegInfo::hostpwd, HostRegInfo::hoststate, HostRegInfo::lastcomtime, LOG_DEBUG, and LOG_ERROR.
int update_db_apprtu (AppRtuInfo & rtuinfo)
update_db_apprtu 修改应用设备
References insert_db_apprtu().
int update_db_detectorbind (DetectorBind & rtuinfo)
update_db_detectorbind 绑定联动接口
Parameters
rtuinfo 绑定的设备信息需要malloc后传入
References RtuBind::add, DetectorBind::bind_num, db_update_query(), RtuBind::delay, DetectorBind::hostadd, DetectorBind::level, RtuBind::oper, DetectorBind::rtuadd, DetectorBind::rtubind, and RtuBind::type.
int update_db_detectorrtu (DetectorRtu & rtuinfo, Uint8 mode)
update_db_detectorrtu 更新传感器设备
Parameters
rtuinfo
mode 模式 0 更新 val 值 1 更新联动标志，阈值 更新val : 传入 val数组值 ,默认为0 更新联动标志： 传入 flag ,downval ,upval
Returns
References db_update_query(), DetectorRtu::detectorinfo, DetectorInfo::downval, DetectorInfo::flag, RtuRegInfo::hostadd, LOG_ERROR, RtuRegInfo::rtuadd, DetectorRtu::rtuinfo, DetectorInfo::upval, DetectorInfo::val, and DetectorRtu::valtype.
int update_db_exnativertu (ExNativeRtu & rtuinfo)
update_db_exnativertu 更新智能床
Parameters
rtuinfo 控制 ： relayinfo 数组 中val值传入 床头位置（1） 床尾位置（1） 床头振动（1） 床尾振动（1） 灯状态（1）：0x00表示关灯，0x01表示开灯
Returns
References db_update_query(), get_table_name(), RtuRegInfo::hostadd, ExNativeRtu::relayinfo, RTU_TYPE_BED, RtuRegInfo::rtuadd, ExNativeRtu::rtuinfo, and RelayInfo::val.
int update_db_host (HostRegInfo & hostinfo)
update_db_host 更新主机信息表
Parameters
hostinfo 更新信息： 传入 hostname ,hostip
Returns
References db_update_query(), findHostname(), get_sys_time(), get_table_name(), HostRegInfo::hostip, HostRegInfo::hostname, LOG_ERROR, and RTU_TYPE_HOST.
int update_db_hostname (HostMan & hostinfo)
update_db_hostname 用户管理
Parameters
hostinfo 更新信息： 传入 原 新 主机名 密码
Returns
References db_select_query(), db_update_query(), MAX_PASSWORD_LEN, HostMan::newname, HostMan::newpwd, HostMan::oldname, and HostMan::oldpwd.
int update_db_nativertu (NativeRtuInfo & rtuinfo, Uint8 mode)
update_db_nativertu 常规设备更新
Parameters
rtuinfo
mode 模式 0 控制 1 绑定负载 控制 ： 传入 RelayInfo 数组中 val 绑定负载： 传入 bind_num , RelayInfo 数组中 id,type,name[] ,path[] 设备头信息 RtuRegInfo 中的hostadd,rtuadd 必须传入
Returns
0 更新成功 -1 更新失败
References NativeRtuInfo::bind_num, db_update_query(), RtuRegInfo::hostadd, RelayInfo::id, LOG_DEBUG, LOG_ERROR, RelayInfo::name, RelayInfo::path, NativeRtuInfo::relayinfo, RtuRegInfo::rtuadd, NativeRtuInfo::rtuinfo, RelayInfo::type, and RelayInfo::val.
int update_db_rtuinfo (RtuUpdate & hostinfo)
update_db_rtuinfo 用户设备信息编辑
Parameters
hostinfo 该结构体所有字段必须传入 更新 设备名称和路径
Returns
References db_update_query(), get_table_name(), RtuUpdate::hostadd, IsNativeRtu(), RtuUpdate::opertype, RTU_TYPE_BED, RTU_TYPE_SCENEINFO, RTU_TYPE_TASKINFO, RtuUpdate::rtuadd, RtuUpdate::rtuname, RtuUpdate::rtupath, and RtuUpdate::rtutype.
int update_db_safetypwd (SafetyPwdInfo & rtuinfo)
update_db_safetypwd 门锁密码更新接口 包括新开锁密码添加，修改 管理员密码修改
References db_select_query(), db_update_query(), SafetyPwdInfo::hostadd, SafetyPwdInfo::id, LOG_ERROR, MAX_PASSWORD_LEN, SafetyPwdInfo::newpwd, SafetyPwdInfo::oldpwd, and SafetyPwdInfo::rtuadd.
int update_db_safetyrtu (SafetyRtu & rtuinfo)
update_db_safetyrtu 更新安防设备
Parameters
rtuinfo 控制： 传入 布防状态 ， 动作状态 hostadd ,rtuadd 必须 传入
Returns
References db_update_query(), get_table_name(), RtuRegInfo::hostadd, SafetyRtu::rtuactstate, RtuRegInfo::rtuadd, SafetyRtu::rtuinfo, SafetyRtu::rtuplace, and RtuRegInfo::rtutype.
int update_db_sceneinfo (SceneInfo & rtuinfo)
update_db_sceneinfo 修改 情景
References insert_db_sceneinfo().
Referenced by main().
int update_db_scenertu (SceneRtu & rtuinfo)
update_db_scenertu 更新情景面板
Parameters
rtuinfo 修改绑定： bind_num , 每个button的信息 ，包括id ,type,add,oper
Returns
References SceneBind::add, SceneRtu::bind_num, db_update_query(), RtuRegInfo::hostadd, SceneBind::id, SceneBind::oper, RtuRegInfo::rtuadd, SceneRtu::rtuinfo, SceneRtu::scene_bind, and SceneBind::type.
int update_db_taskinfo (TaskInfo & taskinfo)
update_db_taskinfo 编辑定时任务
References insert_db_taskinfo().
Referenced by main().
Variable Documentation
const char DB_TABLE_NAMELIST[][32]
Initial value:
=
{
    "HostInfo",
    "NativeRtu",
    "SceneRtu",
    "SceneInfo",
    "TransponRtu",
    "AppRtu",
    "SafetyRtu",
    "SafetyPwdInfo",
    "SafetySetBind",
    "SafetyRemoveBind",
    "SceneInfoContinued",
    "DetectorRtu",
    "DetectorBind",
    "TaskInfo",
    "ExNativeRtu",
    "RtuTypeInfo",
    "UseDevTypeInfo",
}
Referenced by delete_db_host(), insert_db_apprtu(), insert_db_host(), insert_db_rtu(), insert_db_sceneinfo(), insert_db_taskinfo(), and select_db_hostinfo().
DBTypeInfo gTypeInfoList[] static
Initial value:
={
    {0,"HostInfo"},
    {1,"NativeRtu"},
    {2,"SceneRtu"},
    {3,"NativeRtu"},
    {4,"NativeRtu"},
    {5,"NativeRtu"},
    {6,"TransponRtu"},
    {7,"TransponRtu"},
    {8,"NativeRtu"},
    {9,"SafetyRtu"},
    {10,"SafetyRtu"},
    {11,"SafetyRtu"},
    {12,"SafetyRtu"},
    {13,"DetectorRtu"},
    {14,"DetectorRtu"},
    {15,"DetectorRtu"},
    {16,"DetectorRtu"},
    {17,"NativeRtu"},
    {18,"ExNativeRtu"},
    {0xfa,"AppRtu"},
    {0xfc,"TaskInfo"},
    {0xfd,"SceneInfo"},
}
数据表数组
Referenced by get_table_name().