My Project: sql.cpp File Reference
sql.cpp File Reference
测试文件
#include <iostream>
#include <stdio.h>
#include <sstream>
#include "dbbase.h"
Functions
Uint16 LHCharToUint16 (const Uint8 *buf)
Uint32 LHCharToUint32 (const Uint8 *buf)
int main (int argc, char const *argv[])
Variables
MysqlConInfo sql_coninfo ={"localhost","root","123456","test"}
Detailed Description
测试文件
Function Documentation
Uint16 LHCharToUint16 (const Uint8 * buf) inline
将 低高字节转换为 16 位 无符号整型
Referenced by LHCharToUint32().
Uint32 LHCharToUint32 (const Uint8 * buf) inline
将 字节顺序为低高字节集转换为32位无符号整型
References LHCharToUint16().
int main (int argc, char const * argv[])
References RtuBind::add, RtuBind::delay, delete_db_rtu(), get_sys_time(), TaskInfo::hostadd, SceneInfo::hostadd, init_mysql(), RtuBind::oper, RTU_TYPE_SCENEINFO, TaskInfo::rtubind, SceneInfo::rtubind, SceneInfo::rturegtime, SceneInfo::sceneid, SceneInfo::scenename, SceneInfo::scenepicid, SceneInfo::scenertunum, sql_coninfo, TaskInfo::taskid, TaskInfo::taskname, TaskInfo::taskregtime, TaskInfo::taskrtunum, RtuBind::type, update_db_sceneinfo(), and update_db_taskinfo().
Variable Documentation
MysqlConInfo sql_coninfo ={"localhost","root","123456","test"}
Referenced by main().